// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplicationEmployeeManagement.Models
{
    public partial class DetailsEmployee
    {
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSurname { get; set; }
        public string EmployeeDepartment { get; set; }
        public DateTime EmployeeStartDate { get; set; }
        public string EmployeePassword { get; set; }
        public string EmployeeOrManager { get; set; }
    }
}