// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplicationEmployeeManagement.Models
{
    public partial class LeaveRequestEmployee
    {
        public int LeaveRequestId { get; set; }
        public int EmployeeId { get; set; }
        public DateTime LeaveDate { get; set; }
        public string LeaveReason { get; set; }
        public DateTime SubmissionDate { get; set; }
        public bool LeaveStatus { get; set; }
    }
}