// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplicationEmployeeManagement.Models
{
    public partial class ReportEmployee
    {
        public int ReportId { get; set; }
        public int EmployeeId { get; set; }
        public DateTime ReportDate { get; set; }
        public int NoOfHrsWorkedOn { get; set; }
        public string TaskWorkedOn { get; set; }
        public int AddDay { get; set; }
        public string ManagerReport { get; set; }
    }
}